apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  app: guestbook-app
spec:
  selector:
    name: frontend
    app: guestbook-app
  ports:
  - port: 80
    targetPort: 80
    type: LoadBalancer
