apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: guestbook-app
spec:
  replicas: 3
  selector:
    matchLabels:
      name: frontend
      app: guestbook-app
  template:
    metadata:
      labels:
        name: frontend
        app: guestbook-app
    spec:
      containers:
      - name: frontend-container
        image: gcr.io/google-samples/gb-frontend:v4
        ports:
        - containerPort: 80
