apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    app: guestbook-app
spec:
  selector:
    name: redis-db
    app: guestbook-app
  ports:
  - port: 6379
    targetPort: 6379
    type: ClusterIP
